[package]
name = "yogurt"
version = "0.1.0"
authors = ["Francois Stephany <francois@tamere.eu>"]

# `$ cargo run --bin dev-server`
# `$ cargo run --bin yogurt`


[dependencies]
clap = "2.28.0"
reqwest = "0.8.1"